# Diabetes Predictor Notebook

# 6a)

In [20]:
conda install numpy=1.24

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Note: you may need to restart the kernel to use updated packages.

warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package numpy-1.24.3-py310h055cbcc_1 requires python >=3.10,<3.11.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ numpy 1.24**  is installable with the potential options
│  ├─ numpy 1.24.3 would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  ├─ numpy 1.24.3 would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  ├─ numpy 1.24.3 would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  └─ numpy 1.24.3 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.12.* (labeled as 'pin-1')

In [191]:
# Import the class from preprocessors/load_data.py
from preprocessors.load_data import DiabetesDataLoader

# Create an instance of the class and call a method
loader = DiabetesDataLoader(data_dir='data', file_name='sample_diabetes_mellitus_data.csv')

In [192]:
train_df, test_df = loader.load_and_split_data()

In [193]:
train_df

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
9254,185898,137,88.0,28.713767,0,Caucasian,F,157.48,Emergency Department,Accident & Emergency,...,0,11.5,0,0,0,0,1,0,0,1
1561,179718,83,69.0,NaN,0,Caucasian,F,152.40,Floor,Floor,...,0,8.9,0,0,0,0,0,0,0,1
1670,204365,118,61.0,NaN,0,Caucasian,M,188.00,NaN,Accident & Emergency,...,0,10.2,0,0,0,0,0,0,0,0
6087,167361,118,36.0,33.861606,1,African American,F,165.10,Operating Room,Operating Room / Recovery,...,1,30.9,0,0,0,0,0,0,0,0
6669,213013,83,49.0,22.693954,1,Caucasian,F,162.60,Operating Room,Operating Room / Recovery,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,232888,118,86.0,NaN,0,Caucasian,F,160.00,Emergency Department,Accident & Emergency,...,0,31.4,0,0,0,0,0,0,0,1
5191,210825,118,68.0,32.549816,1,African American,M,176.50,Operating Room,Operating Room / Recovery,...,0,12.6,0,0,0,0,0,0,0,0
5390,240686,151,54.0,24.509470,1,Caucasian,M,162.60,NaN,Operating Room / Recovery,...,0,10.6,0,0,0,0,0,0,0,0
860,231954,33,87.0,28.566361,0,Caucasian,M,172.70,Emergency Department,Accident & Emergency,...,1,20.4,0,0,0,0,0,0,0,0
7270,185737,118,60.0,19.400691,1,Caucasian,M,170.20,Operating Room,Operating Room / Recovery,...,0,16.6,0,0,0,0,0,0,0,0

First we are imputing the mean for height and weight, and then we will drop null values

# 6c)

In [194]:


class Preprocessor_fill:
    def __init__(self):
        self.columns_to_fill = ['height', 'weight']  # Columns to fill with mean

    def fill_nan_with_mean(self, df):
        # For each column in the columns_to_fill, replace NaN values with the mean
        for column in self.columns_to_fill:
            print(f"Processing column: {column}")

            # Print the column data before processing (for debugging purposes)
            print(f"Before conversion to numeric: \n{df[column].head()}")

            # Convert the column to numeric (coerce any non-numeric values to NaN)
            df[column] = pd.to_numeric(df[column], errors='coerce')

            # Print the column data after conversion to numeric (for debugging purposes)
            print(f"After conversion to numeric: \n{df[column].head()}")

            # Calculate the mean of the column
            mean_value = df[column].mean()
            print(f"Mean of '{column}': {mean_value}")  # Debugging print

            # Fill NaN values with the column mean
            df[column] = df[column].fillna(mean_value)

            # Print the column data after filling NaN values
            print(f"After filling NaN: \n{df[column].head()}")
        
        return df

preprocessors_fill = Preprocessor_fill()

In [195]:
train_df_clean = preprocessors_fill.fill_nan_with_mean(train_df)

Processing column: height
Before conversion to numeric:
9254    157.48
1561    152.40
1670    188.00
6087    165.10
6669    162.60
Name: height, dtype: float64
After conversion to numeric:
9254    157.48
1561    152.40
1670    188.00
6087    165.10
6669    162.60
Name: height, dtype: float64
Mean of 'height': 169.75811085685228
After filling NaN:
9254    157.48
1561    152.40
1670    188.00
6087    165.10
6669    162.60
Name: height, dtype: float64
Processing column: weight
Before conversion to numeric:
9254    71.21
1561      NaN
1670      NaN
6087    92.30
6669    60.00
Name: weight, dtype: float64
After conversion to numeric:
9254    71.21
1561      NaN
1670      NaN
6087    92.30
6669    60.00
Name: weight, dtype: float64
Mean of 'weight': 85.99043445804716
After filling NaN:
9254    71.210000
1561    85.990434
1670    85.990434
6087    92.300000
6669    60.000000
Name: weight, dtype: float64

In [188]:
# Assuming train_df_clean is already defined

# Count the number of NaN values in each column
null_count = train_df_clean.isna().sum()

# Get the total number of rows in the DataFrame
total_rows = train_df_clean.shape[0]

# Display the null count and total number of rows
print("Null count for each column:")
print(null_count)

print(f"\nTotal number of rows in the DataFrame: {total_rows}")

Null count for each column:
encounter_id                      0
hospital_id                       0
age                             325
bmi                            1367
elective_surgery                  0
ethnicity                       193
gender                            3
height                         8000
hospital_admit_source           748
icu_admit_source                 17
icu_id                            0
icu_stay_type                     0
icu_type                          0
pre_icu_los_days                  0
readmission_status                0
weight                         8000
albumin_apache                 5161
apache_2_diagnosis              145
apache_3j_diagnosis              41
apache_post_operative             0
arf_apache                        0
bilirubin_apache               5275
bun_apache                     2010
creatinine_apache              1896
fio2_apache                    5666
gcs_eyes_apache                  57
gcs_motor_apache                 57
gcs_unable_apache                53
gcs_verbal_apache                57
glucose_apache                  859
heart_rate_apache                 0
hematocrit_apache              1597
intubated_apache                  0
map_apache                       10
paco2_apache                   5666
paco2_for_ph_apache            5666
pao2_apache                    5666
ph_apache                      5666
resprate_apache                  30
sodium_apache                  1965
temp_apache                      78
urineoutput_apache             6785
ventilated_apache                 0
wbc_apache                     1758
aids                              0
cirrhosis                         0
hepatic_failure                   0
immunosuppression                 0
leukemia                          0
lymphoma                          0
solid_tumor_with_metastasis       0
diabetes_mellitus                 0
dtype: int64

Total number of rows in the DataFrame: 8000

In [165]:
train_df_clean

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
9254,185898,137,88.0,28.713767,0,Caucasian,F,None,Emergency Department,Accident & Emergency,...,0,11.5,0,0,0,0,1,0,0,1
1561,179718,83,69.0,NaN,0,Caucasian,F,None,Floor,Floor,...,0,8.9,0,0,0,0,0,0,0,1
1670,204365,118,61.0,NaN,0,Caucasian,M,None,NaN,Accident & Emergency,...,0,10.2,0,0,0,0,0,0,0,0
6087,167361,118,36.0,33.861606,1,African American,F,None,Operating Room,Operating Room / Recovery,...,1,30.9,0,0,0,0,0,0,0,0
6669,213013,83,49.0,22.693954,1,Caucasian,F,None,Operating Room,Operating Room / Recovery,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,232888,118,86.0,NaN,0,Caucasian,F,None,Emergency Department,Accident & Emergency,...,0,31.4,0,0,0,0,0,0,0,1
5191,210825,118,68.0,32.549816,1,African American,M,None,Operating Room,Operating Room / Recovery,...,0,12.6,0,0,0,0,0,0,0,0
5390,240686,151,54.0,24.509470,1,Caucasian,M,None,NaN,Operating Room / Recovery,...,0,10.6,0,0,0,0,0,0,0,0
860,231954,33,87.0,28.566361,0,Caucasian,M,None,Emergency Department,Accident & Emergency,...,1,20.4,0,0,0,0,0,0,0,0
7270,185737,118,60.0,19.400691,1,Caucasian,M,None,Operating Room,Operating Room / Recovery,...,0,16.6,0,0,0,0,0,0,0,0

# 6b)

In [130]:
# Import the class
from preprocessors.drop_na_preprocessor import Preprocessor_drop

# Create an instance
preprocessors_drop = Preprocessor_drop()

In [131]:
train_df_non_na = preprocessors_drop.remove_nan_rows(train_df)
test_df_non_na =  preprocessors_drop.remove_nan_rows(test_df)

In [136]:
# Assuming train_df_clean is already defined

# Count the number of NaN values in each column
null_count =train_df_non_na.isna().sum()

# Get the total number of rows in the DataFrame
total_rows =train_df_non_na.shape[0]

# Display the null count and total number of rows
print("Null count for each column:")
print(null_count)

print(f"\nTotal number of rows in the DataFrame: {total_rows}")

Null count for each column:
encounter_id                      0
hospital_id                       0
age                               0
bmi                            1275
elective_surgery                  0
ethnicity                         0
gender                            0
height                         7494
hospital_admit_source           693
icu_admit_source                 17
icu_id                            0
icu_stay_type                     0
icu_type                          0
pre_icu_los_days                  0
readmission_status                0
weight                         7494
albumin_apache                 4834
apache_2_diagnosis              143
apache_3j_diagnosis              40
apache_post_operative             0
arf_apache                        0
bilirubin_apache               4941
bun_apache                     1895
creatinine_apache              1787
fio2_apache                    5264
gcs_eyes_apache                  53
gcs_motor_apache                 53
gcs_unable_apache                49
gcs_verbal_apache                53
glucose_apache                  799
heart_rate_apache                 0
hematocrit_apache              1500
intubated_apache                  0
map_apache                        9
paco2_apache                   5264
paco2_for_ph_apache            5264
pao2_apache                    5264
ph_apache                      5264
resprate_apache                  26
sodium_apache                  1853
temp_apache                      66
urineoutput_apache             6394
ventilated_apache                 0
wbc_apache                     1646
aids                              0
cirrhosis                         0
hepatic_failure                   0
immunosuppression                 0
leukemia                          0
lymphoma                          0
solid_tumor_with_metastasis       0
diabetes_mellitus                 0
dtype: int64

Total number of rows in the DataFrame: 7494

# 6 c)

In [132]:
# Import the class
from preprocessors.fill_na_preprocessor import Preprocessor_fill
# Create an Instance
preprocessors_fill = Preprocessor_fill()

In [134]:
train_df_clean = preprocessors_fill.fill_nan_with_mean(train_df_non_na)
test_df_clean = preprocessors_fill.fill_nan_with_mean(test_df_non_na)

c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\preprocessors\fill_na_preprocessor.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[:, column] = df[column].fillna(mean_value, inplace=True)

In [135]:
# Assuming train_df_clean is already defined

# Count the number of NaN values in each column
null_count = train_df_clean.isna().sum()

# Get the total number of rows in the DataFrame
total_rows = train_df_clean.shape[0]

# Display the null count and total number of rows
print("Null count for each column:")
print(null_count)

print(f"\nTotal number of rows in the DataFrame: {total_rows}")

Null count for each column:
encounter_id                      0
hospital_id                       0
age                               0
bmi                            1275
elective_surgery                  0
ethnicity                         0
gender                            0
height                         7494
hospital_admit_source           693
icu_admit_source                 17
icu_id                            0
icu_stay_type                     0
icu_type                          0
pre_icu_los_days                  0
readmission_status                0
weight                         7494
albumin_apache                 4834
apache_2_diagnosis              143
apache_3j_diagnosis              40
apache_post_operative             0
arf_apache                        0
bilirubin_apache               4941
bun_apache                     1895
creatinine_apache              1787
fio2_apache                    5264
gcs_eyes_apache                  53
gcs_motor_apache                 53
gcs_unable_apache                49
gcs_verbal_apache                53
glucose_apache                  799
heart_rate_apache                 0
hematocrit_apache              1500
intubated_apache                  0
map_apache                        9
paco2_apache                   5264
paco2_for_ph_apache            5264
pao2_apache                    5264
ph_apache                      5264
resprate_apache                  26
sodium_apache                  1853
temp_apache                      66
urineoutput_apache             6394
ventilated_apache                 0
wbc_apache                     1646
aids                              0
cirrhosis                         0
hepatic_failure                   0
immunosuppression                 0
leukemia                          0
lymphoma                          0
solid_tumor_with_metastasis       0
diabetes_mellitus                 0
dtype: int64

Total number of rows in the DataFrame: 7494

# 6 d)

In [52]:
# Import the class
from feature_extractors.feature_transformer_1 import GenderFeature,EthnicityFeature

# Create an Instance
GenderFeature_creation = GenderFeature()
EthnicityFeature_creation = EthnicityFeature()

In [53]:
#Feature 1 creation
train_df_feature_1 = GenderFeature_creation.transform(train_df_clean)
test_df_feature_1 = GenderFeature_creation.transform(test_df_clean)

c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\feature_extractors\feature_transformer_1.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'gender_encoded'] = df['gender'].apply(lambda x: 1 if x == 'M' else 0)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\feature_extractors\feature_transformer_1.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'gender_encoded'] = df['gender'].apply(lambda x: 1 if x == 'M' else 0)

In [54]:
#Feature 2 creation
train_df_feature_2 = EthnicityFeature_creation.transform(train_df_feature_1)
test_df_feature_2 = EthnicityFeature_creation.transform(test_df_feature_1)

c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\feature_extractors\feature_transformer_1.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'ethnicity_encoded'] = df['ethnicity'].map(ethnicity_mapping).fillna(-1).astype(int)
c:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\feature_extractors\feature_transformer_1.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'ethnicity_encoded'] = df['ethnicity'].map(ethnicity_mapping).fillna(-1).astype(int)

# 6 e)

In [63]:
train_df_feature_2

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,...,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus,gender_encoded,ethnicity_encoded
9254,185898,137,88.0,28.713767,0,Caucasian,F,None,Emergency Department,Accident & Emergency,...,0,0,0,0,1,0,0,1,0,0
1561,179718,83,69.0,NaN,0,Caucasian,F,None,Floor,Floor,...,0,0,0,0,0,0,0,1,0,0
1670,204365,118,61.0,NaN,0,Caucasian,M,None,NaN,Accident & Emergency,...,0,0,0,0,0,0,0,0,1,0
6087,167361,118,36.0,33.861606,1,African American,F,None,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,0,0,0,0,2
6669,213013,83,49.0,22.693954,1,Caucasian,F,None,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,232888,118,86.0,NaN,0,Caucasian,F,None,Emergency Department,Accident & Emergency,...,0,0,0,0,0,0,0,1,0,0
5191,210825,118,68.0,32.549816,1,African American,M,None,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,0,0,0,1,2
5390,240686,151,54.0,24.509470,1,Caucasian,M,None,NaN,Operating Room / Recovery,...,0,0,0,0,0,0,0,0,1,0
860,231954,33,87.0,28.566361,0,Caucasian,M,None,Emergency Department,Accident & Emergency,...,0,0,0,0,0,0,0,0,1,0
7270,185737,118,60.0,19.400691,1,Caucasian,M,None,Operating Room,Operating Room / Recovery,...,0,0,0,0,0,0,0,0,1,0

In [59]:
# Import the class
from models.model import Model

In [62]:
# Create an Instance

#feature columns and target column
target_column = 'diabetes_mellitus'
feature_columns = ['age', 'gender_encoded', 'ethnicity_encoded','height', 'weight']
##
model_instance = Model(feature_columns=feature_columns, target_column=target_column)

In [65]:
# Count the number of NaN values in each of the specified columns
nan_count = train_df_feature_2[feature_columns].isna().sum()

# Display the count of NaN values in each column
print(nan_count)

age                     0
gender_encoded          0
ethnicity_encoded       0
height               7494
weight               7494
dtype: int64

In [64]:
# Train the model

model_instance.train(train_df_feature_2)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values