Testing of the functions

# a)  Load data

In [1]:
conda install numpy=1.24

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Note: you may need to restart the kernel to use updated packages.

warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package numpy-1.24.3-py310h055cbcc_1 requires python >=3.10,<3.11.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ numpy 1.24**  is installable with the potential options
│  ├─ numpy 1.24.3 would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  ├─ numpy 1.24.3 would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  ├─ numpy 1.24.3 would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  └─ numpy 1.24.3 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.12.* (labeled as 'pin-1')

In [4]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split

class DiabetesDataLoader:
    def __init__(self, data_dir='../data', file_name='sample_diabetes_mellitus_data.csv', test_size=0.2, random_state=42):
        self.file_path = os.path.join(data_dir, file_name)
        self.test_size = test_size
        self.random_state = random_state

    def load_and_split_data(self):
        #Primary method that loads the data and splits it into train and test DataFrames.
        
        # Load the CSV data
        df = pd.read_csv(self.file_path, index_col=0)

        # Split the data into training and testing sets
        train_df, test_df = train_test_split(df, test_size=self.test_size, random_state=self.random_state)

        return train_df, test_df


# Example of how to use the class
data_loader = DiabetesDataLoader()
train_df, test_df = data_loader.load_and_split_data()

In [5]:
train_df

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
9254,185898,137,88.0,28.713767,0,Caucasian,F,157.48,Emergency Department,Accident & Emergency,...,0,11.5,0,0,0,0,1,0,0,1
1561,179718,83,69.0,NaN,0,Caucasian,F,152.40,Floor,Floor,...,0,8.9,0,0,0,0,0,0,0,1
1670,204365,118,61.0,NaN,0,Caucasian,M,188.00,NaN,Accident & Emergency,...,0,10.2,0,0,0,0,0,0,0,0
6087,167361,118,36.0,33.861606,1,African American,F,165.10,Operating Room,Operating Room / Recovery,...,1,30.9,0,0,0,0,0,0,0,0
6669,213013,83,49.0,22.693954,1,Caucasian,F,162.60,Operating Room,Operating Room / Recovery,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,232888,118,86.0,NaN,0,Caucasian,F,160.00,Emergency Department,Accident & Emergency,...,0,31.4,0,0,0,0,0,0,0,1
5191,210825,118,68.0,32.549816,1,African American,M,176.50,Operating Room,Operating Room / Recovery,...,0,12.6,0,0,0,0,0,0,0,0
5390,240686,151,54.0,24.509470,1,Caucasian,M,162.60,NaN,Operating Room / Recovery,...,0,10.6,0,0,0,0,0,0,0,0
860,231954,33,87.0,28.566361,0,Caucasian,M,172.70,Emergency Department,Accident & Emergency,...,1,20.4,0,0,0,0,0,0,0,0
7270,185737,118,60.0,19.400691,1,Caucasian,M,170.20,Operating Room,Operating Room / Recovery,...,0,16.6,0,0,0,0,0,0,0,0

In [6]:
test_df

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
6252,275141,81,66.0,34.852863,0,Caucasian,M,180.30,Emergency Department,Accident & Emergency,...,1,7.6,0,0,0,0,0,0,0,1
4684,269942,118,NaN,18.593750,0,Caucasian,F,160.00,NaN,Accident & Emergency,...,0,6.9,0,0,0,0,0,0,0,0
1731,183562,118,83.0,28.215375,0,Caucasian,F,154.90,Other Hospital,Other Hospital,...,1,19.6,0,0,0,0,0,0,0,0
4742,244929,118,64.0,21.575502,1,Caucasian,F,170.20,Emergency Department,Operating Room / Recovery,...,0,10.0,0,0,0,1,0,0,0,0
4521,193781,118,21.0,34.560280,1,African American,F,162.00,Operating Room,Operating Room / Recovery,...,1,18.0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6412,183270,118,80.0,20.087932,0,Caucasian,F,162.60,Emergency Department,Accident & Emergency,...,1,8.5,0,0,0,0,0,0,0,0
8285,254168,89,80.0,22.326705,0,Caucasian,F,162.56,Direct Admit,Accident & Emergency,...,0,6.4,0,0,0,0,0,0,0,0
7853,269140,81,59.0,NaN,0,Caucasian,M,160.00,Emergency Department,Accident & Emergency,...,0,16.8,0,0,0,0,0,0,0,0
1095,201230,83,79.0,25.311715,1,Caucasian,M,167.60,Operating Room,Operating Room / Recovery,...,0,14.9,0,0,0,0,0,0,0,0
6929,240583,77,72.0,NaN,1,Caucasian,M,182.90,Operating Room,Operating Room / Recovery,...,1,19.9,0,0,0,0,0,0,0,0

In [7]:
df = pd.read_csv(r"C:\Users\aleja\OneDrive\Escritorio\BSE_ACADEMIC\computing_for_data_science\HW5\diabetes-predictor\diabetes_predictor\data\sample_diabetes_mellitus_data.csv")

In [8]:
df = df.drop(columns=['Unnamed: 0'])
df

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
0,214826,118,68.0,22.732803,0,Caucasian,M,180.30,Floor,Floor,...,0,14.1,0,0,0,0,0,0,0,1
1,246060,81,77.0,27.421875,0,Caucasian,F,160.00,Floor,Floor,...,1,12.7,0,0,0,0,0,0,0,1
2,276985,118,25.0,31.952749,0,Caucasian,F,172.70,Emergency Department,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
3,262220,118,81.0,22.635548,1,Caucasian,F,165.10,Operating Room,Operating Room / Recovery,...,1,8.0,0,0,0,0,0,0,0,0
4,201746,33,19.0,NaN,0,Caucasian,M,188.00,NaN,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,167042,140,NaN,51.952814,0,Caucasian,F,137.20,Floor,Floor,...,0,7.0,0,0,0,0,0,0,0,0
9996,165009,89,34.0,26.110113,0,Caucasian,F,175.26,Emergency Department,Accident & Emergency,...,0,9.5,0,0,0,0,0,0,0,0
9997,234052,137,30.0,23.774241,0,Native American,F,157.48,Emergency Department,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
9998,249290,89,67.0,31.330708,0,Caucasian,F,157.48,Direct Admit,Accident & Emergency,...,0,6.4,0,0,0,0,0,0,0,0
9999,151312,89,55.0,44.343663,0,Caucasian,F,157.50,Emergency Department,Accident & Emergency,...,1,NaN,0,0,0,0,0,0,0,0

In [9]:
# Summary of NaN values per column
nan_summary = df.isnull().sum()

# Display the summary
print("Summary of NaN values per column:")
print(nan_summary)

Summary of NaN values per column:
encounter_id                      0
hospital_id                       0
age                             405
bmi                            1738
elective_surgery                  0
ethnicity                       242
gender                            3
height                          160
hospital_admit_source           918
icu_admit_source                 21
icu_id                            0
icu_stay_type                     0
icu_type                          0
pre_icu_los_days                  0
readmission_status                0
weight                         1658
albumin_apache                 6461
apache_2_diagnosis              180
apache_3j_diagnosis              51
apache_post_operative             0
arf_apache                        0
bilirubin_apache               6592
bun_apache                     2521
creatinine_apache              2389
fio2_apache                    7087
gcs_eyes_apache                  69
gcs_motor_apache                 69
gcs_unable_apache                65
gcs_verbal_apache                69
glucose_apache                 1085
heart_rate_apache                 1
hematocrit_apache              2006
intubated_apache                  0
map_apache                       13
paco2_apache                   7087
paco2_for_ph_apache            7087
pao2_apache                    7087
ph_apache                      7087
resprate_apache                  39
sodium_apache                  2466
temp_apache                     101
urineoutput_apache             8477
ventilated_apache                 0
wbc_apache                     2198
aids                              0
cirrhosis                         0
hepatic_failure                   0
immunosuppression                 0
leukemia                          0
lymphoma                          0
solid_tumor_with_metastasis       0
diabetes_mellitus                 0
dtype: int64

# b) preprocessor drop na

In [10]:
import pandas as pd

class Preprocessor_drop:
    def __init__(self):

        self.columns_to_check = ['age', 'gender', 'ethnicity']

    def remove_nan_rows(self, df):
        # Drop rows with NaN values in the 'age', 'gender', and 'ethnicity' columns
        df_cleaned = df.dropna(subset=self.columns_to_check)
        return df_cleaned

In [11]:

    # Create an instance of Preprocessor
    preprocessor_drop = Preprocessor_drop()

    # Remove rows with NaN values in 'age', 'gender', and 'ethnicity' columns
    df_cleaned = preprocessor_drop.remove_nan_rows(df)

In [12]:
df_cleaned

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
0,214826,118,68.0,22.732803,0,Caucasian,M,180.30,Floor,Floor,...,0,14.1,0,0,0,0,0,0,0,1
1,246060,81,77.0,27.421875,0,Caucasian,F,160.00,Floor,Floor,...,1,12.7,0,0,0,0,0,0,0,1
2,276985,118,25.0,31.952749,0,Caucasian,F,172.70,Emergency Department,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
3,262220,118,81.0,22.635548,1,Caucasian,F,165.10,Operating Room,Operating Room / Recovery,...,1,8.0,0,0,0,0,0,0,0,0
4,201746,33,19.0,NaN,0,Caucasian,M,188.00,NaN,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,271449,89,78.0,28.700475,0,Caucasian,F,172.70,Emergency Department,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
9996,165009,89,34.0,26.110113,0,Caucasian,F,175.26,Emergency Department,Accident & Emergency,...,0,9.5,0,0,0,0,0,0,0,0
9997,234052,137,30.0,23.774241,0,Native American,F,157.48,Emergency Department,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
9998,249290,89,67.0,31.330708,0,Caucasian,F,157.48,Direct Admit,Accident & Emergency,...,0,6.4,0,0,0,0,0,0,0,0
9999,151312,89,55.0,44.343663,0,Caucasian,F,157.50,Emergency Department,Accident & Emergency,...,1,NaN,0,0,0,0,0,0,0,0

In [13]:
# Summary of NaN values per column
nan_summary = df_cleaned.isnull().sum()

# Display the summary
print("Summary of NaN values per column:")
print(nan_summary)

Summary of NaN values per column:
encounter_id                      0
hospital_id                       0
age                               0
bmi                            1622
elective_surgery                  0
ethnicity                         0
gender                            0
height                          127
hospital_admit_source           850
icu_admit_source                 21
icu_id                            0
icu_stay_type                     0
icu_type                          0
pre_icu_los_days                  0
readmission_status                0
weight                         1556
albumin_apache                 6046
apache_2_diagnosis              177
apache_3j_diagnosis              49
apache_post_operative             0
arf_apache                        0
bilirubin_apache               6170
bun_apache                     2372
creatinine_apache              2247
fio2_apache                    6583
gcs_eyes_apache                  65
gcs_motor_apache                 65
gcs_unable_apache                61
gcs_verbal_apache                65
glucose_apache                 1008
heart_rate_apache                 1
hematocrit_apache              1879
intubated_apache                  0
map_apache                       12
paco2_apache                   6583
paco2_for_ph_apache            6583
pao2_apache                    6583
ph_apache                      6583
resprate_apache                  33
sodium_apache                  2321
temp_apache                      85
urineoutput_apache             7981
ventilated_apache                 0
wbc_apache                     2054
aids                              0
cirrhosis                         0
hepatic_failure                   0
immunosuppression                 0
leukemia                          0
lymphoma                          0
solid_tumor_with_metastasis       0
diabetes_mellitus                 0
dtype: int64

# C) preprocessor fill

In [14]:
import pandas as pd

class Preprocessor_fill:
    def __init__(self):
      
        self.columns_to_fill = ['height', 'weight']

    def fill_nan_with_mean(self, df):

        # For each column in the columns_to_fill, replace NaN values with the mean
        for column in self.columns_to_fill:

            mean_value = df[column].mean()
            df[column].fillna(mean_value, inplace=True)

        return df

In [15]:

    # Create an instance of Preprocessor
    preprocessor_fill = Preprocessor_fill()

    # Fill NaN values in 'height' and 'weight' columns with the mean of each column
    df_filled = preprocessor_fill.fill_nan_with_mean(df_cleaned)

C:\Users\aleja\AppData\Local\Temp\ipykernel_27092\2508339939.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(mean_value, inplace=True)
C:\Users\aleja\AppData\Local\Temp\ipykernel_27092\2508339939.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column].fillna(mean_value, inplace=True)

In [16]:
df_filled

,encounter_id,hospital_id,age,bmi,elective_surgery,ethnicity,gender,height,hospital_admit_source,icu_admit_source,...,ventilated_apache,wbc_apache,aids,cirrhosis,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,diabetes_mellitus
0,214826,118,68.0,22.732803,0,Caucasian,M,180.30,Floor,Floor,...,0,14.1,0,0,0,0,0,0,0,1
1,246060,81,77.0,27.421875,0,Caucasian,F,160.00,Floor,Floor,...,1,12.7,0,0,0,0,0,0,0,1
2,276985,118,25.0,31.952749,0,Caucasian,F,172.70,Emergency Department,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
3,262220,118,81.0,22.635548,1,Caucasian,F,165.10,Operating Room,Operating Room / Recovery,...,1,8.0,0,0,0,0,0,0,0,0
4,201746,33,19.0,NaN,0,Caucasian,M,188.00,NaN,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,271449,89,78.0,28.700475,0,Caucasian,F,172.70,Emergency Department,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
9996,165009,89,34.0,26.110113,0,Caucasian,F,175.26,Emergency Department,Accident & Emergency,...,0,9.5,0,0,0,0,0,0,0,0
9997,234052,137,30.0,23.774241,0,Native American,F,157.48,Emergency Department,Accident & Emergency,...,0,NaN,0,0,0,0,0,0,0,0
9998,249290,89,67.0,31.330708,0,Caucasian,F,157.48,Direct Admit,Accident & Emergency,...,0,6.4,0,0,0,0,0,0,0,0
9999,151312,89,55.0,44.343663,0,Caucasian,F,157.50,Emergency Department,Accident & Emergency,...,1,NaN,0,0,0,0,0,0,0,0

In [17]:
# Summary of NaN values per column
nan_summary = df_filled.isnull().sum()

# Display the summary
print("Summary of NaN values per column:")
print(nan_summary)

Summary of NaN values per column:
encounter_id                      0
hospital_id                       0
age                               0
bmi                            1622
elective_surgery                  0
ethnicity                         0
gender                            0
height                            0
hospital_admit_source           850
icu_admit_source                 21
icu_id                            0
icu_stay_type                     0
icu_type                          0
pre_icu_los_days                  0
readmission_status                0
weight                            0
albumin_apache                 6046
apache_2_diagnosis              177
apache_3j_diagnosis              49
apache_post_operative             0
arf_apache                        0
bilirubin_apache               6170
bun_apache                     2372
creatinine_apache              2247
fio2_apache                    6583
gcs_eyes_apache                  65
gcs_motor_apache                 65
gcs_unable_apache                61
gcs_verbal_apache                65
glucose_apache                 1008
heart_rate_apache                 1
hematocrit_apache              1879
intubated_apache                  0
map_apache                       12
paco2_apache                   6583
paco2_for_ph_apache            6583
pao2_apache                    6583
ph_apache                      6583
resprate_apache                  33
sodium_apache                  2321
temp_apache                      85
urineoutput_apache             7981
ventilated_apache                 0
wbc_apache                     2054
aids                              0
cirrhosis                         0
hepatic_failure                   0
immunosuppression                 0
leukemia                          0
lymphoma                          0
solid_tumor_with_metastasis       0
diabetes_mellitus                 0
dtype: int64

# d) Feature classes

In [18]:
# Assuming df is your DataFrame
unique_ethnicities = df['ethnicity'].unique()

# Display the unique values
print("Unique values in the 'ethnicity' column:")
print(unique_ethnicities)

Unique values in the 'ethnicity' column:
['Caucasian' nan 'Hispanic' 'African American' 'Asian' 'Native American'
 'Other/Unknown']

In [19]:
# diabetes_predictor/feature_extractors/feature_transformer_1.py
from abc import ABC, abstractmethod
import pandas as pd

class Feature(ABC):
    @abstractmethod
    def transform(self, df: pd.DataFrame) -> pd.DataFrame:
        pass

##Feature transformation 1, geneder to binary

class GenderFeature(Feature):
    def transform(self, df: pd.DataFrame) -> pd.DataFrame:
        #Encode the 'gender' column where:
        # 1 represents Male
        # 0 represents Female
        df['gender_encoded'] = df['gender'].apply(lambda x: 1 if x == 'M' else 0)
        return df
    
##Feature transformation 2, categories for ethnicity

class EthnicityFeature(Feature):
    def transform(self, df: pd.DataFrame) -> pd.DataFrame:

        # Define the mapping for ethnicity
        ethnicity_mapping = {
            'Caucasian': 0,
            'Hispanic': 1,
            'African American': 2,
            'Asian': 3,
            'Native American': 4,
            'Other/Unknown': 5
        }
        
        # Apply the mapping, using -1 for NaN values
        df['ethnicity_encoded'] = df['ethnicity'].map(ethnicity_mapping).fillna(-1).astype(int)
        
        return df

# e) - # f)

In [20]:
from sklearn.linear_model import LogisticRegression

class Model:
    def __init__(self, feature_columns, target_column, **model_hyperparams):

        self.__feature_columns = feature_columns  # Private attribute for feature columns
        self.__target_column = target_column      # Private attribute for target column
        self.__model_hyperparams = model_hyperparams  # Private attribute for model hyperparameters

        # Public attribute for the logistic regression model
        self.model = LogisticRegression(**self.__model_hyperparams)

    def train(self, df):
      
        #Train the model using the provided training data.
        # Extract features (X) and target (y) from the DataFrame
        X_train = df[self.__feature_columns]  # Select the feature columns
        y_train = df[self.__target_column]    # Select the target column

        # Train the logistic regression model
        self.model.fit(X_train, y_train)

    def predict(self, df):

        #Predict the probabilities on new data using the trained model.

        #Parameters:
        # pandas DataFrame containing the data for prediction.
        #Returns:
        #Predicted probabilities for each class.
        
        # Select feature columns for prediction
        X_test = df[self.__feature_columns]
        
        # Return the predicted probabilities
        return self.model.predict_proba(X_test)